Allow install even with asterisk > 17
NethServer/nethserver-freepbx pull request #74
Opened 2022-03-17 16:59 UTC by Stell0

https://github.com/nethesis/dev/issues/6124

2022-03-30 12:10 UTC, gsanchietti requested changes

2022-03-30 12:10 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-freepbx-conf-scl
> +
```suggestion
```

2022-03-30 12:10 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-freepbx-conf
> +	echo -e '[modules]\nautoload=no' > /etc/asterisk/modules.conf
Please include the file inside freepbx package or, better, inside asterisk one

2022-03-30 12:10 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-freepbx-conf
> +	sed -i 's/if (version_compare(\$version, "11", "lt") || version_compare(\$version, "17", "ge")) {/if (version_compare(\$version, "11", "lt") || version_compare(\$version, "19", "ge")) {/' /usr/src/f
These files are part of rpm, your are going to break package integrity.
Please create a patch to be applied by the spec

2022-04-01 15:37 UTC, Stell0 commented
patch made here https://github.com/NethServer/freepbx/pull/8 and modules.conf here https://github.com/NethServer/asterisk13/pull/29

2022-04-01 15:37 UTC, closed without merging